// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#include "game.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `softmax:game/output@0.1.0`

__attribute__((__import_module__("softmax:game/output@0.1.0"), __import_name__("results")))
extern void __wasm_import_softmax_game_output_results(uint8_t *, size_t);

__attribute__((__import_module__("softmax:game/output@0.1.0"), __import_name__("replay-append")))
extern void __wasm_import_softmax_game_output_replay_append(uint8_t *, size_t);

// Imported Functions from `softmax:game/log@0.1.0`

__attribute__((__import_module__("softmax:game/log@0.1.0"), __import_name__("line")))
extern void __wasm_import_softmax_game_log_line(uint8_t *, size_t, uint8_t *, size_t);

// Exported Functions from `game`

__attribute__((__weak__, __export_name__("cabi_post_init")))
void __wasm_export_exports_game_init_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_step")))
void __wasm_export_exports_game_step_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len0 = *((size_t*) (arg0 + (2*sizeof(void*))));
      if (len0 > 0) {
        uint8_t *ptr1 = *((uint8_t **) (arg0 + sizeof(void*)));
        for (size_t i2 = 0; i2 < len0; i2++) {
          uint8_t *base = ptr1 + i2 * (3*sizeof(void*));
          (void) base;
          size_t len = *((size_t*) (base + (2*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (base + sizeof(void*)));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
        }
        free(ptr1);
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_finish")))
void __wasm_export_exports_game_finish_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(4*sizeof(void*))];

// Helper Functions

void game_list_u8_free(game_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void softmax_game_types_seat_message_free(softmax_game_types_seat_message_t *ptr) {
  game_list_u8_free(&ptr->payload);
}

void softmax_game_types_list_seat_message_free(softmax_game_types_list_seat_message_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    softmax_game_types_seat_message_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      softmax_game_types_seat_message_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void softmax_game_types_step_output_free(softmax_game_types_step_output_t *ptr) {
  softmax_game_types_list_seat_message_free(&ptr->messages);
}

void game_seat_message_free(game_seat_message_t *ptr) {
  softmax_game_types_seat_message_free(ptr);
}

void game_step_output_free(game_step_output_t *ptr) {
  softmax_game_types_step_output_free(ptr);
}

void game_result_void_string_free(game_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    game_string_free(&ptr->val.err);
  }
}

void game_list_seat_message_free(game_list_seat_message_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    game_seat_message_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      game_seat_message_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void game_result_step_output_string_free(game_result_step_output_string_t *ptr) {
  if (!ptr->is_err) {
    game_step_output_free(&ptr->val.ok);
  } else {
    game_string_free(&ptr->val.err);
  }
}

void game_string_set(game_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void game_string_dup(game_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void game_string_dup_n(game_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void game_string_free(game_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void softmax_game_output_results(game_list_u8_t *body) {
  __wasm_import_softmax_game_output_results((uint8_t *) (*body).ptr, (*body).len);
}

void softmax_game_output_replay_append(game_list_u8_t *chunk) {
  __wasm_import_softmax_game_output_replay_append((uint8_t *) (*chunk).ptr, (*chunk).len);
}

void softmax_game_log_line(game_string_t *level, game_string_t *msg) {
  __wasm_import_softmax_game_log_line((uint8_t *) (*level).ptr, (*level).len, (uint8_t *) (*msg).ptr, (*msg).len);
}

__attribute__((__export_name__("init")))
uint8_t * __wasm_export_exports_game_init(uint8_t * arg, size_t arg0, int32_t arg1, int64_t arg2) {
  game_string_t arg3 = (game_string_t) { (uint8_t*)(arg), (arg0) };
  game_result_void_string_t ret;
  game_string_t err;
  ret.is_err = !exports_game_init(&arg3, (uint32_t) (arg1), (uint64_t) (arg2), &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const game_string_t *payload4 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload4).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload4).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("step")))
uint8_t * __wasm_export_exports_game_step(uint8_t * arg, size_t arg0) {
  game_list_seat_message_t arg1 = (game_list_seat_message_t) { (game_seat_message_t*)(arg), (arg0) };
  game_result_step_output_string_t ret;
  game_step_output_t ok;
  game_string_t err;
  ret.is_err = !exports_game_step(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const game_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload2).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload2).ptr;
  } else {
    const game_step_output_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = ((*payload).messages).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) ((*payload).messages).ptr;
    *((int8_t*)(ptr + (3*sizeof(void*)))) = (*payload).done;
  }
  return ptr;
}

__attribute__((__export_name__("finish")))
uint8_t * __wasm_export_exports_game_finish(void) {
  game_result_void_string_t ret;
  game_string_t err;
  ret.is_err = !exports_game_finish(&err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const game_string_t *payload0 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload0).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload0).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_game(void);
__attribute__((used))
void __component_type_object_force_link_game_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_game();
}
