## Regenerates src/ctf/map_pool.nim: scans seeds upward and keeps the first
## ones whose map passes every validator on the FIRST attempt (so the pool
## entry IS the map — no re-roll drift if validators tighten later), under
## small size-class and endzone-shape quotas for variety.
## Usage: nim c -r tools/gen_map_pool.nim [startSeed]
## Demo/curation tooling; not part of the server.
import std/[os, strutils, strformat], ../src/ctf/sim

const
  PoolSize = 20
  SizeQuota = [4, 5, 4, 4, 3]  ## small, standard, large, huge, giant.
  ShapeQuota = [10, 5, 5]      ## column, disc, square.

proc sizeClassIndex(gameMap: CtfMap): int =
  case gameMap.width
  of 1050: 0
  of 1235: 1
  of 1606: 2
  of 2223: 3
  of 3211: 4
  else:
    raise newException(CtfError, "Unexpected map width: " & $gameMap.width)

proc shapeIndex(gameMap: CtfMap): int =
  case gameMap.endzone
  of ezColumn: 0
  of ezDisc: 1
  of ezSquare: 2

when isMainModule:
  let start = if paramCount() >= 1: parseInt(paramStr(1)) else: 1001
  var
    seeds: seq[int]
    counts = [0, 0, 0, 0, 0]
    shapeCounts = [0, 0, 0]
    seed = start
    scanned, rejected = 0
  while seeds.len < PoolSize:
    let gameMap = generateMapAttempt(seed, MapGenOverrides(windows: -1, pits: -1, pitDensity: -1))
    inc scanned
    let reason = validateGeneratedMap(gameMap)
    if reason.len > 0:
      inc rejected
      echo &"seed={seed} REJECT {reason}"
    else:
      let
        sizeIndex = gameMap.sizeClassIndex()
        shape = gameMap.shapeIndex()
      if counts[sizeIndex] < SizeQuota[sizeIndex] and
          shapeCounts[shape] < ShapeQuota[shape]:
        seeds.add seed
        inc counts[sizeIndex]
        inc shapeCounts[shape]
        echo &"pool[{seeds.len - 1}] seed={seed} " &
          &"{gameMap.width}x{gameMap.height} sym={gameMap.symmetry} " &
          &"endzone={gameMap.endzone} r={gameMap.endzoneRadius} " &
          &"home={gameMap.teamHomeX(Red)} " &
          &"obstacles={gameMap.leftObstacles.len}"
      else:
        echo &"seed={seed} ok but quota full"
    stdout.flushFile()
    inc seed
  echo &"scanned={scanned} rejected={rejected}"

  var lines = @[
    "## GENERATED by `nim c -r tools/gen_map_pool.nim` — do not edit by hand.",
    "## The curated terrain pool: seeds whose generated maps pass every " &
      "validator",
    "## on their FIRST attempt (so the pool entry IS the map, no re-roll " &
      "drift).",
    "",
    "const MapPoolSeeds*: array[" & $PoolSize & ", int] = [",
  ]
  for i in countup(0, PoolSize - 1, 10):
    var chunk: seq[string]
    for j in i ..< min(i + 10, PoolSize):
      chunk.add $seeds[j]
    lines.add "  " & chunk.join(", ") & ","
  lines.add "]"
  let outPath =
    currentSourcePath.parentDir.parentDir / "src" / "ctf" / "map_pool.nim"
  writeFile(outPath, lines.join("\n") & "\n")
  echo "wrote ", outPath
