// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#include "player.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `softmax:player/log@0.1.0`

__attribute__((__import_module__("softmax:player/log@0.1.0"), __import_name__("line")))
extern void __wasm_import_softmax_player_log_line(uint8_t *, size_t, uint8_t *, size_t);

// Exported Functions from `player`

__attribute__((__weak__, __export_name__("cabi_post_start")))
void __wasm_export_exports_player_start_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_on-message")))
void __wasm_export_exports_player_on_message_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len0 = *((size_t*) (arg0 + (2*sizeof(void*))));
      if (len0 > 0) {
        uint8_t *ptr1 = *((uint8_t **) (arg0 + sizeof(void*)));
        for (size_t i2 = 0; i2 < len0; i2++) {
          uint8_t *base = ptr1 + i2 * (2*sizeof(void*));
          (void) base;
          size_t len = *((size_t*) (base + sizeof(void*)));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (base + 0));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
        }
        free(ptr1);
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void player_option_string_free(player_option_string_t *ptr) {
  if (ptr->is_some) {
    player_string_free(&ptr->val);
  }
}

void player_result_void_string_free(player_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    player_string_free(&ptr->val.err);
  }
}

void player_list_u8_free(player_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void player_list_list_u8_free(player_list_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    player_list_u8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      player_list_u8_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void player_result_list_list_u8_string_free(player_result_list_list_u8_string_t *ptr) {
  if (!ptr->is_err) {
    player_list_list_u8_free(&ptr->val.ok);
  } else {
    player_string_free(&ptr->val.err);
  }
}

void player_string_set(player_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void player_string_dup(player_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void player_string_dup_n(player_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void player_string_free(player_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void softmax_player_log_line(player_string_t *level, player_string_t *msg) {
  __wasm_import_softmax_player_log_line((uint8_t *) (*level).ptr, (*level).len, (uint8_t *) (*msg).ptr, (*msg).len);
}

__attribute__((__export_name__("start")))
uint8_t * __wasm_export_exports_player_start(int32_t arg, int32_t arg0, uint8_t * arg1, size_t arg2) {
  player_option_string_t option;
  switch (arg0) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (player_string_t) { (uint8_t*)(arg1), (arg2) };
      break;
    }
  }
  player_result_void_string_t ret;
  player_string_t err;
  ret.is_err = !exports_player_start((uint32_t) (arg), option.is_some ? &(option.val) : NULL, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const player_string_t *payload3 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload3).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload3).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("on-message")))
uint8_t * __wasm_export_exports_player_on_message(uint8_t * arg, size_t arg0) {
  player_list_u8_t arg1 = (player_list_u8_t) { (uint8_t*)(arg), (arg0) };
  player_result_list_list_u8_string_t ret;
  player_list_list_u8_t ok;
  player_string_t err;
  ret.is_err = !exports_player_on_message(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const player_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload2).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload2).ptr;
  } else {
    const player_list_list_u8_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_player(void);
__attribute__((used))
void __component_type_object_force_link_player_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_player();
}
